#!/bin/bash

#This script will check whether the package is installed.

# Prompt user for package name.

echo "Enter the name of the package to check installation status: "

read packagename

# Check if package is installed. Tell user whether package is installed or not.

if ! dpkg-query -l $packagename &> /dev/null; then

    echo "The $packagename package is not installed.";

    exit

    else echo "The $packagename package is installed.";

    exit

fi
